### ISSUE TITLE
Json serizalbe equalty etc

### ISSUE THREAD

**Issue by VB10** [yavuzfk/flutter_foot_order_app#1]
https://github.com/yavuzfk/flutter_food_order_app/blob/374b1ad093419170536a56d2547655f22d737288/lib/entitiy/food_model.dart#L15

modellerin muhakkak equaltyden turemelei or final olmali refreance type sorunu yasmamak icin
modellerini json serizlable ile uretmelsin
dartj kualanbirsn

**Comment by yavuzfk** [comment]
Json serializaiton a göre düzenledim hocam, teşekkürler.
