### ISSUE TITLE
Json json

### ISSUE THREAD

**Issue by VB10** [yavuzfk/flutter_foot_order_app#2]
https://github.com/yavuzfk/flutter_food_order_app/blob/374b1ad093419170536a56d2547655f22d737288/lib/entitiy/sepet_answer.dart#L6

isimlendirme turkce olmaz
json srialble again

**Comment by yavuzfk** [comment]
List yapısını json serializable a göre düzenleme kısmına tekrar bakacağım, isimlendirmeyi hallettim, teşekkürler.
