### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by VB10** [yavuzfk/flutter_foot_order_app#3]
https://github.com/yavuzfk/flutter_food_order_app/blob/374b1ad093419170536a56d2547655f22d737288/lib/utilities/string_items.dart#L7

bu tarz base urllerini env icinde tutup buradan okuyaiblrisin sadece sonuna path ekleyere kulalnrisin
bunda enum extenson yapalbrisn

**Comment by yavuzfk** [comment]
Path leri enum haline getirip extension la kullandım, teşekkürler.
