### ISSUE TITLE
sayfa icinde

### ISSUE THREAD

**Issue by VB10** [yavuzfk/flutter_foot_order_app#6]
https://github.com/yavuzfk/flutter_food_order_app/blob/374b1ad093419170536a56d2547655f22d737288/lib/views/order_page/order_page.dart#L19

asla sinfi disinda veri tutma 
cubit varsa tum islemlerin cubit icinde olmali like tutar
cubitindek methdoalr en olmali

**Comment by yavuzfk** [comment]
tamamdır
