### ISSUE TITLE
Theme parcalama

### ISSUE THREAD

**Issue by VB10** [yavuzfk/flutter_foot_order_app#8]
https://github.com/yavuzfk/flutter_food_order_app/blob/374b1ad093419170536a56d2547655f22d737288/lib/views/order_page/widgets/siparis_button.dart#L48

hem cok static kod var bunlar stadnart olmali
ikincisi icerdiek oeprasyonlada transform vs ayirlmali paddingler sabit olmali
container degil sizebox gibi empty vlauler veirlmeli or
if x != null widget gibi kulalnlmali

**Comment by yavuzfk** [comment]
İlgili class larda comment le belirttiğim üzere o butonun görsel kısmını ben geliştirmedim, görselliği arttırmak amacıyla kullandım. Lakin geliştirmelerimde söylediğiniz konulara daha fazla dikkat edeceğim, teşekkürler.
