### ISSUE TITLE
isim cubit

### ISSUE THREAD

**Issue by VB10** [yavuzfk/flutter_foot_order_app#9]
https://github.com/yavuzfk/flutter_food_order_app/blob/374b1ad093419170536a56d2547655f22d737288/lib/cubit/anasayfa_cubit.dart#L8

stateini lsit olark degil daha global saklamalisin custom. bir class uzerinden loading vs de koymak icin
isimdlenrimed ing olmali
cubit icerisinde var ile degil final ile o valunu saklamasin ve private olmali

**Comment by yavuzfk** [comment]
İlk yazdığınız konuyu araştırmam lazım deneyimlemedim, diğerlerini hallettim teşekkürler.
